#ifndef LHTML_FIELD_NAMES
#define LHTML_FIELD_NAMES

#define LHTML_FIELD_NAME_CHARACTER character
#define LHTML_FIELD_NAME_COMMENT comment
#define LHTML_FIELD_NAME_START_TAG start_tag
#define LHTML_FIELD_NAME_END_TAG end_tag
#define LHTML_FIELD_NAME_DOCTYPE doctype
#define LHTML_FIELD_NAME_EOF eof

#endif
