/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tests.proto */

#ifndef PROTOBUF_C_tests_2eproto__INCLUDED
#define PROTOBUF_C_tests_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Suite Suite;
typedef struct _Suite__Test Suite__Test;
typedef struct _Suite__Test__Doctype Suite__Test__Doctype;
typedef struct _Suite__Test__Attribute Suite__Test__Attribute;
typedef struct _Suite__Test__StartTag Suite__Test__StartTag;
typedef struct _Suite__Test__EndTag Suite__Test__EndTag;
typedef struct _Suite__Test__Comment Suite__Test__Comment;
typedef struct _Suite__Test__Character Suite__Test__Character;
typedef struct _Suite__Test__Token Suite__Test__Token;


/* --- enums --- */

typedef enum _Suite__Test__State {
  SUITE__TEST__STATE__DATA = 1,
  SUITE__TEST__STATE__PLAINTEXT = 2,
  SUITE__TEST__STATE__RCDATA = 3,
  SUITE__TEST__STATE__RAWTEXT = 4,
  SUITE__TEST__STATE__SCRIPTDATA = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SUITE__TEST__STATE)
} Suite__Test__State;

/* --- messages --- */

struct  _Suite__Test__Doctype
{
  ProtobufCMessage base;
  protobuf_c_boolean has_name;
  ProtobufCBinaryData name;
  protobuf_c_boolean has_public_id;
  ProtobufCBinaryData public_id;
  protobuf_c_boolean has_system_id;
  ProtobufCBinaryData system_id;
  protobuf_c_boolean force_quirks;
};
#define SUITE__TEST__DOCTYPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&suite__test__doctype__descriptor) \
    , 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0 }


struct  _Suite__Test__Attribute
{
  ProtobufCMessage base;
  ProtobufCBinaryData name;
  ProtobufCBinaryData value;
};
#define SUITE__TEST__ATTRIBUTE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&suite__test__attribute__descriptor) \
    , {0,NULL}, {0,NULL} }


struct  _Suite__Test__StartTag
{
  ProtobufCMessage base;
  ProtobufCBinaryData name;
  size_t n_attributes;
  Suite__Test__Attribute **attributes;
  protobuf_c_boolean self_closing;
};
#define SUITE__TEST__START_TAG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&suite__test__start_tag__descriptor) \
    , {0,NULL}, 0,NULL, 0 }


struct  _Suite__Test__EndTag
{
  ProtobufCMessage base;
  ProtobufCBinaryData name;
};
#define SUITE__TEST__END_TAG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&suite__test__end_tag__descriptor) \
    , {0,NULL} }


struct  _Suite__Test__Comment
{
  ProtobufCMessage base;
  ProtobufCBinaryData value;
};
#define SUITE__TEST__COMMENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&suite__test__comment__descriptor) \
    , {0,NULL} }


struct  _Suite__Test__Character
{
  ProtobufCMessage base;
  ProtobufCBinaryData value;
};
#define SUITE__TEST__CHARACTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&suite__test__character__descriptor) \
    , {0,NULL} }


typedef enum {
  SUITE__TEST__TOKEN__TOKEN__NOT_SET = 0,
  SUITE__TEST__TOKEN__TOKEN_DOCTYPE = 1,
  SUITE__TEST__TOKEN__TOKEN_START_TAG = 2,
  SUITE__TEST__TOKEN__TOKEN_END_TAG = 3,
  SUITE__TEST__TOKEN__TOKEN_COMMENT = 4,
  SUITE__TEST__TOKEN__TOKEN_CHARACTER = 5,
} Suite__Test__Token__TokenCase;

struct  _Suite__Test__Token
{
  ProtobufCMessage base;
  Suite__Test__Token__TokenCase token_case;
  union {
    Suite__Test__Doctype *doctype;
    Suite__Test__StartTag *start_tag;
    Suite__Test__EndTag *end_tag;
    Suite__Test__Comment *comment;
    Suite__Test__Character *character;
  };
};
#define SUITE__TEST__TOKEN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&suite__test__token__descriptor) \
    , SUITE__TEST__TOKEN__TOKEN__NOT_SET, {0} }


struct  _Suite__Test
{
  ProtobufCMessage base;
  ProtobufCBinaryData description;
  ProtobufCBinaryData input;
  size_t n_output;
  Suite__Test__Token **output;
  size_t n_initial_states;
  Suite__Test__State *initial_states;
  ProtobufCBinaryData last_start_tag;
};
#define SUITE__TEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&suite__test__descriptor) \
    , {0,NULL}, {0,NULL}, 0,NULL, 0,NULL, {0,NULL} }


struct  _Suite
{
  ProtobufCMessage base;
  size_t n_tests;
  Suite__Test **tests;
  protobuf_c_boolean with_feedback;
};
#define SUITE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&suite__descriptor) \
    , 0,NULL, 0 }


/* Suite__Test__Doctype methods */
void   suite__test__doctype__init
                     (Suite__Test__Doctype         *message);
/* Suite__Test__Attribute methods */
void   suite__test__attribute__init
                     (Suite__Test__Attribute         *message);
/* Suite__Test__StartTag methods */
void   suite__test__start_tag__init
                     (Suite__Test__StartTag         *message);
/* Suite__Test__EndTag methods */
void   suite__test__end_tag__init
                     (Suite__Test__EndTag         *message);
/* Suite__Test__Comment methods */
void   suite__test__comment__init
                     (Suite__Test__Comment         *message);
/* Suite__Test__Character methods */
void   suite__test__character__init
                     (Suite__Test__Character         *message);
/* Suite__Test__Token methods */
void   suite__test__token__init
                     (Suite__Test__Token         *message);
/* Suite__Test methods */
void   suite__test__init
                     (Suite__Test         *message);
/* Suite methods */
void   suite__init
                     (Suite         *message);
size_t suite__get_packed_size
                     (const Suite   *message);
size_t suite__pack
                     (const Suite   *message,
                      uint8_t             *out);
size_t suite__pack_to_buffer
                     (const Suite   *message,
                      ProtobufCBuffer     *buffer);
Suite *
       suite__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   suite__free_unpacked
                     (Suite *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Suite__Test__Doctype_Closure)
                 (const Suite__Test__Doctype *message,
                  void *closure_data);
typedef void (*Suite__Test__Attribute_Closure)
                 (const Suite__Test__Attribute *message,
                  void *closure_data);
typedef void (*Suite__Test__StartTag_Closure)
                 (const Suite__Test__StartTag *message,
                  void *closure_data);
typedef void (*Suite__Test__EndTag_Closure)
                 (const Suite__Test__EndTag *message,
                  void *closure_data);
typedef void (*Suite__Test__Comment_Closure)
                 (const Suite__Test__Comment *message,
                  void *closure_data);
typedef void (*Suite__Test__Character_Closure)
                 (const Suite__Test__Character *message,
                  void *closure_data);
typedef void (*Suite__Test__Token_Closure)
                 (const Suite__Test__Token *message,
                  void *closure_data);
typedef void (*Suite__Test_Closure)
                 (const Suite__Test *message,
                  void *closure_data);
typedef void (*Suite_Closure)
                 (const Suite *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor suite__descriptor;
extern const ProtobufCMessageDescriptor suite__test__descriptor;
extern const ProtobufCMessageDescriptor suite__test__doctype__descriptor;
extern const ProtobufCMessageDescriptor suite__test__attribute__descriptor;
extern const ProtobufCMessageDescriptor suite__test__start_tag__descriptor;
extern const ProtobufCMessageDescriptor suite__test__end_tag__descriptor;
extern const ProtobufCMessageDescriptor suite__test__comment__descriptor;
extern const ProtobufCMessageDescriptor suite__test__character__descriptor;
extern const ProtobufCMessageDescriptor suite__test__token__descriptor;
extern const ProtobufCEnumDescriptor    suite__test__state__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_tests_2eproto__INCLUDED */
