/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tests.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "tests.pb-c.h"
void   suite__test__doctype__init
                     (Suite__Test__Doctype         *message)
{
  static Suite__Test__Doctype init_value = SUITE__TEST__DOCTYPE__INIT;
  *message = init_value;
}
void   suite__test__attribute__init
                     (Suite__Test__Attribute         *message)
{
  static Suite__Test__Attribute init_value = SUITE__TEST__ATTRIBUTE__INIT;
  *message = init_value;
}
void   suite__test__start_tag__init
                     (Suite__Test__StartTag         *message)
{
  static Suite__Test__StartTag init_value = SUITE__TEST__START_TAG__INIT;
  *message = init_value;
}
void   suite__test__end_tag__init
                     (Suite__Test__EndTag         *message)
{
  static Suite__Test__EndTag init_value = SUITE__TEST__END_TAG__INIT;
  *message = init_value;
}
void   suite__test__comment__init
                     (Suite__Test__Comment         *message)
{
  static Suite__Test__Comment init_value = SUITE__TEST__COMMENT__INIT;
  *message = init_value;
}
void   suite__test__character__init
                     (Suite__Test__Character         *message)
{
  static Suite__Test__Character init_value = SUITE__TEST__CHARACTER__INIT;
  *message = init_value;
}
void   suite__test__token__init
                     (Suite__Test__Token         *message)
{
  static Suite__Test__Token init_value = SUITE__TEST__TOKEN__INIT;
  *message = init_value;
}
void   suite__test__init
                     (Suite__Test         *message)
{
  static Suite__Test init_value = SUITE__TEST__INIT;
  *message = init_value;
}
void   suite__init
                     (Suite         *message)
{
  static Suite init_value = SUITE__INIT;
  *message = init_value;
}
size_t suite__get_packed_size
                     (const Suite *message)
{
  assert(message->base.descriptor == &suite__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t suite__pack
                     (const Suite *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &suite__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t suite__pack_to_buffer
                     (const Suite *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &suite__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Suite *
       suite__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Suite *)
     protobuf_c_message_unpack (&suite__descriptor,
                                allocator, len, data);
}
void   suite__free_unpacked
                     (Suite *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &suite__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor suite__test__doctype__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Suite__Test__Doctype, has_name),
    offsetof(Suite__Test__Doctype, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Suite__Test__Doctype, has_public_id),
    offsetof(Suite__Test__Doctype, public_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Suite__Test__Doctype, has_system_id),
    offsetof(Suite__Test__Doctype, system_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "force_quirks",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Suite__Test__Doctype, force_quirks),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned suite__test__doctype__field_indices_by_name[] = {
  3,   /* field[3] = force_quirks */
  0,   /* field[0] = name */
  1,   /* field[1] = public_id */
  2,   /* field[2] = system_id */
};
static const ProtobufCIntRange suite__test__doctype__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor suite__test__doctype__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Suite.Test.Doctype",
  "Doctype",
  "Suite__Test__Doctype",
  "",
  sizeof(Suite__Test__Doctype),
  4,
  suite__test__doctype__field_descriptors,
  suite__test__doctype__field_indices_by_name,
  1,  suite__test__doctype__number_ranges,
  (ProtobufCMessageInit) suite__test__doctype__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor suite__test__attribute__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Suite__Test__Attribute, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Suite__Test__Attribute, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned suite__test__attribute__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange suite__test__attribute__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor suite__test__attribute__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Suite.Test.Attribute",
  "Attribute",
  "Suite__Test__Attribute",
  "",
  sizeof(Suite__Test__Attribute),
  2,
  suite__test__attribute__field_descriptors,
  suite__test__attribute__field_indices_by_name,
  1,  suite__test__attribute__number_ranges,
  (ProtobufCMessageInit) suite__test__attribute__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor suite__test__start_tag__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Suite__Test__StartTag, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributes",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Suite__Test__StartTag, n_attributes),
    offsetof(Suite__Test__StartTag, attributes),
    &suite__test__attribute__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "self_closing",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Suite__Test__StartTag, self_closing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned suite__test__start_tag__field_indices_by_name[] = {
  1,   /* field[1] = attributes */
  0,   /* field[0] = name */
  2,   /* field[2] = self_closing */
};
static const ProtobufCIntRange suite__test__start_tag__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor suite__test__start_tag__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Suite.Test.StartTag",
  "StartTag",
  "Suite__Test__StartTag",
  "",
  sizeof(Suite__Test__StartTag),
  3,
  suite__test__start_tag__field_descriptors,
  suite__test__start_tag__field_indices_by_name,
  1,  suite__test__start_tag__number_ranges,
  (ProtobufCMessageInit) suite__test__start_tag__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor suite__test__end_tag__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Suite__Test__EndTag, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned suite__test__end_tag__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange suite__test__end_tag__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor suite__test__end_tag__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Suite.Test.EndTag",
  "EndTag",
  "Suite__Test__EndTag",
  "",
  sizeof(Suite__Test__EndTag),
  1,
  suite__test__end_tag__field_descriptors,
  suite__test__end_tag__field_indices_by_name,
  1,  suite__test__end_tag__number_ranges,
  (ProtobufCMessageInit) suite__test__end_tag__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor suite__test__comment__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Suite__Test__Comment, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned suite__test__comment__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange suite__test__comment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor suite__test__comment__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Suite.Test.Comment",
  "Comment",
  "Suite__Test__Comment",
  "",
  sizeof(Suite__Test__Comment),
  1,
  suite__test__comment__field_descriptors,
  suite__test__comment__field_indices_by_name,
  1,  suite__test__comment__number_ranges,
  (ProtobufCMessageInit) suite__test__comment__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor suite__test__character__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Suite__Test__Character, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned suite__test__character__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange suite__test__character__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor suite__test__character__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Suite.Test.Character",
  "Character",
  "Suite__Test__Character",
  "",
  sizeof(Suite__Test__Character),
  1,
  suite__test__character__field_descriptors,
  suite__test__character__field_indices_by_name,
  1,  suite__test__character__number_ranges,
  (ProtobufCMessageInit) suite__test__character__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor suite__test__token__field_descriptors[5] =
{
  {
    "doctype",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Suite__Test__Token, token_case),
    offsetof(Suite__Test__Token, doctype),
    &suite__test__doctype__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_tag",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Suite__Test__Token, token_case),
    offsetof(Suite__Test__Token, start_tag),
    &suite__test__start_tag__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_tag",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Suite__Test__Token, token_case),
    offsetof(Suite__Test__Token, end_tag),
    &suite__test__end_tag__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "comment",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Suite__Test__Token, token_case),
    offsetof(Suite__Test__Token, comment),
    &suite__test__comment__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "character",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Suite__Test__Token, token_case),
    offsetof(Suite__Test__Token, character),
    &suite__test__character__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned suite__test__token__field_indices_by_name[] = {
  4,   /* field[4] = character */
  3,   /* field[3] = comment */
  0,   /* field[0] = doctype */
  2,   /* field[2] = end_tag */
  1,   /* field[1] = start_tag */
};
static const ProtobufCIntRange suite__test__token__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor suite__test__token__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Suite.Test.Token",
  "Token",
  "Suite__Test__Token",
  "",
  sizeof(Suite__Test__Token),
  5,
  suite__test__token__field_descriptors,
  suite__test__token__field_indices_by_name,
  1,  suite__test__token__number_ranges,
  (ProtobufCMessageInit) suite__test__token__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue suite__test__state__enum_values_by_number[5] =
{
  { "DATA", "SUITE__TEST__STATE__DATA", 1 },
  { "PLAINTEXT", "SUITE__TEST__STATE__PLAINTEXT", 2 },
  { "RCDATA", "SUITE__TEST__STATE__RCDATA", 3 },
  { "RAWTEXT", "SUITE__TEST__STATE__RAWTEXT", 4 },
  { "SCRIPTDATA", "SUITE__TEST__STATE__SCRIPTDATA", 5 },
};
static const ProtobufCIntRange suite__test__state__value_ranges[] = {
{1, 0},{0, 5}
};
static const ProtobufCEnumValueIndex suite__test__state__enum_values_by_name[5] =
{
  { "DATA", 0 },
  { "PLAINTEXT", 1 },
  { "RAWTEXT", 3 },
  { "RCDATA", 2 },
  { "SCRIPTDATA", 4 },
};
const ProtobufCEnumDescriptor suite__test__state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Suite.Test.State",
  "State",
  "Suite__Test__State",
  "",
  5,
  suite__test__state__enum_values_by_number,
  5,
  suite__test__state__enum_values_by_name,
  1,
  suite__test__state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor suite__test__field_descriptors[5] =
{
  {
    "description",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Suite__Test, description),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Suite__Test, input),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Suite__Test, n_output),
    offsetof(Suite__Test, output),
    &suite__test__token__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "initial_states",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Suite__Test, n_initial_states),
    offsetof(Suite__Test, initial_states),
    &suite__test__state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_start_tag",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Suite__Test, last_start_tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned suite__test__field_indices_by_name[] = {
  0,   /* field[0] = description */
  3,   /* field[3] = initial_states */
  1,   /* field[1] = input */
  4,   /* field[4] = last_start_tag */
  2,   /* field[2] = output */
};
static const ProtobufCIntRange suite__test__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor suite__test__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Suite.Test",
  "Test",
  "Suite__Test",
  "",
  sizeof(Suite__Test),
  5,
  suite__test__field_descriptors,
  suite__test__field_indices_by_name,
  1,  suite__test__number_ranges,
  (ProtobufCMessageInit) suite__test__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor suite__field_descriptors[2] =
{
  {
    "tests",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Suite, n_tests),
    offsetof(Suite, tests),
    &suite__test__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "with_feedback",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Suite, with_feedback),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned suite__field_indices_by_name[] = {
  0,   /* field[0] = tests */
  1,   /* field[1] = with_feedback */
};
static const ProtobufCIntRange suite__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor suite__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Suite",
  "Suite",
  "Suite",
  "",
  sizeof(Suite),
  2,
  suite__field_descriptors,
  suite__field_indices_by_name,
  1,  suite__number_ranges,
  (ProtobufCMessageInit) suite__init,
  NULL,NULL,NULL    /* reserved[123] */
};
